### ISSUE TITLE
Win + E works, but it can't merge new windows when presssing Show in folder

### ISSUE THREAD

**Issue by Jinnm** [w4po/ExplorerTabUtility#3]
I've turned on all three options in the menu. Does it support win11? But this program really helps me a lot!

**Comment by w4po** [comment]
Hello,
Does opening a new window not merge too, or just 'show in folder'?

Have you changed your Windows 11 look by any chance? by using any tool such as StartAllBack?

What OS build and version do you have and which edition? Home, Pro?

**Comment by w4po** [comment]
Hello @Jinnm 
I've published a new release today, [v1.2.0](https://github.com/w4po/ExplorerTabUtility/releases).

Under `All Windows` Select `Keys`.
Please let me know if that fixes the issue for you.

**Comment by Jinnm** [comment]
> Hello, Does opening a new window not merge too, or just 'show in folder'?
> 
> Have you changed your Windows 11 look by any chance? by using any tool such as StartAllBack?
> 
> What OS build and version do you have and which edition? Home, Pro?

I did use this plugin [https://github.com/valinet/ExplorerPatcher/wiki/All-features] to change the taskbar to the left side of the screen. And v1.2.0 works! Thanks a lot!
